// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local (in addition to .env) — this project keeps its single source of
// secrets in .env.local. Values already present in the process env win (avoid clobbering
// dotenv-cli exports used by `bunx dotenv -e .env.local -- bunx prisma ...`).
dotenv.config({ path: ".env.local" });

function resolveDatabaseUrl(env: NodeJS.ProcessEnv = process.env): string {
  const explicit = env.DATABASE_URL;
  if (explicit) return explicit;

  const isProduction =
    env.VERCEL_ENV === "production" ||
    (env.VERCEL_ENV !== "preview" && env.NODE_ENV === "production");

  const url = isProduction ? env.DATABASE_PROD_URL : env.DATABASE_DEVELOPMENT_URL;

  if (!url) {
    throw new Error(
      "No database URL configured. Set DATABASE_URL, or DATABASE_PROD_URL / " +
        "DATABASE_DEVELOPMENT_URL for the current environment.",
    );
  }

  return url;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: resolveDatabaseUrl(),
  },
});